"""migracion modelos

Revision ID: 54d28efe2a56
Revises: 30a381477f26
Create Date: 2025-03-20 14:26:46.471966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54d28efe2a56'
down_revision: Union[str, None] = '30a381477f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producto_id'), 'producto', ['id'], unique=False)
    op.create_table('maquinaproducto',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_maquina', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_maquina'], ['maquinas.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maquinaproducto_id'), 'maquinaproducto', ['id'], unique=False)
    op.create_table('venta',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_maquina_producto', sa.Integer(), nullable=True),
    sa.Column('sales', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_maquina_producto'], ['maquinaproducto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venta_id'), 'venta', ['id'], unique=False)
    op.add_column('maquinas', sa.Column('ubication', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maquinas', 'ubication')
    op.drop_index(op.f('ix_venta_id'), table_name='venta')
    op.drop_table('venta')
    op.drop_index(op.f('ix_maquinaproducto_id'), table_name='maquinaproducto')
    op.drop_table('maquinaproducto')
    op.drop_index(op.f('ix_producto_id'), table_name='producto')
    op.drop_table('producto')
    # ### end Alembic commands ###
